### ISSUE TITLE
@GenerationValue startegy test

### ISSUE THREAD

**Issue by doongdang** [doongdangOrg/DamnGoodTeample#2]
## To Do
- [x] DB Engine 
- [x] Auto Increment(MySQL) VS Sequence(H2) 작동 방식
- [x] @GenerationValue(strategy=IDENTITY)와 SEQUENCE가 각각 H2와 MySQL에서 어떻게 작동할지 확인
- [x] 최종적으로 IDENTITY 전략과 SEQUENCE 전략의 차이

## 배운점

1. JPA를 사용할 때는 편리함에 속아 넘어가면 안된다. 보여주는 결과는 같을 수 있지만, 내부 동작은 예상과 다르게 진행될 수 있기 때문이다. 만일 MySQL을 사용하는데 @GenerationValue(strategy=SEQUENCE)를 선택했다면, MySQL에는 SEQUENCE가 없기 때문에 이를 흉내내기 위해 seq 테이블을 생성하게 된다.  즉, Oracle이나 H2에서의 Sequence 결과는 같지만 그 과정은 전혀 다르다.

2. 보다 효율적인 코드를 짜기 위해서는, 사용되는 요소 하나하나를 제대로 이해하고 있어야 한다. 어떤 원리로 동작하는지, 사용되는 자료구조는 어떤 것인지 등등

**Comment by InSooBae** [comment]
LGTM
